### ISSUE TITLE
Can't select Refresh in VR Desktop mode

### ISSUE THREAD

**Issue by Krzeszny** [KinectToVR/Amethyst-Releases#8]
When using VR desktop, pressing the trigger on Refresh always results in this drop-down menu. Pressing Disconnect from the drop-down menu always closes the drop-down menu. There's no way to refresh anything that has a drop-down menu without using the mouse cursor. 

How to repro (tested on Reverb G2 with WMR controllers):

1. Open WMR Desktop in VR
2. Go to an Amethyst menu that has a drop-down button, for example Devices
3. Try to refresh with a controller's trigger
4. Result example:
![Amethyst_bbl9hPaJ2b](https://github.com/KinectToVR/Amethyst-Releases/assets/10529134/1885f566-6935-4498-a348-f44d75125842)

**Comment by KimihikoAkayasaki** [comment]
It's probably because of how SteamVR handles input from WMR, supposedly the same as Oculus – tablet-mode like. Please try clicking another controller button, registered for left mouse click (and not touch) or aiming more to the left side of the button.

Either way, this concrete behavior cannot be solved from Amethyst's side, except for workarounds at least. You might want to join our Discord server to as for other people's workarounds, if applicable.

Thanks for using Amethyst!

BTW If you need to click 'Refresh' every time and are using Xbox One Kinect, this is also a relatively known bug – not tested thoroughly enough yet, though.
